Domain Interface
ajktown/docs pull request #78
Opened 2024-02-14 20:28 UTC by mlajkim

# Background
TODO: Write the background. If you have an issue related to it, you can simply put the URL

## TODOs
- [ ] TODO: Write your TODOs.
- [ ] TODO: If your issue has TODOs, please copy appropriate ones here.

## Checklist (Developers)
- [ ] `Draft` is set for this PR
- [ ] `Title` is checked
- [ ] `Background` is filled
- [ ] `TODOs` are filled
- [ ] `Assignee` is set
- [ ] `Labels` are set
- [ ] `Project` is created & linked, if multiple PRs are associated to this PR
- [ ] `development` is linked if related issue exists
- [ ] `yarn inspect` is run
- [ ] `TODOs` are handled and checked
- [ ] Final Operation Check is done
- [ ] Make this PR as an open PR

## Checklist (Reviewers)
- [ ] Check if there are any other missing TODOs that are not yet listed
- [ ] Review Code
- [ ] Every item on the checklist has been addressed accordingly
- [ ] If `development` is associated to this PR, you must check if every TODOs are handled

2024-02-18 11:35 UTC, emanisay27 approved these changes

2024-02-18 11:35 UTC, emanisay27 commented on dev/writing_conventions/api/domain-interface.md
> +- [Domain Interface](#domain-interface)
Emanisay27@domain.com

2024-02-18 11:35 UTC, emanisay27 commented on dev/writing_conventions/api/domain-interface.md
> +- [Domain Interface](#domain-interface)
Hi

2024-02-18 11:35 UTC, emanisay27 commented on dev/writing_conventions/api/domain-interface.md
> +  - [Overview](#overview)
Heloo My name is Emmanuel Burton Sarmiento 39 from philippines

2024-02-18 11:37 UTC, emanisay27 approved these changes

2024-02-18 11:37 UTC, emanisay27 commented on dev/writing_conventions/api/domain-interface.md
> +  - [Managed Prefix](#managed-prefix)
Emmanuel_ Burton_Sarmiento-Overview

2024-02-18 11:38 UTC, emanisay27 approved these changes

2024-02-18 11:38 UTC, emanisay27 commented on dev/writing_conventions/api/domain-interface.md
> +  - [Managed Name](#managed-name)
Emmanuel Burton Sarmiento

2024-02-18 11:47 UTC, emanisay27 approved these changes

2024-02-18 11:47 UTC, emanisay27 commented on dev/writing_conventions/api/domain-interface.md
> +  - [Managed Prefix](#managed-prefix)
Emmanuel Burton Sarmiento

2024-02-18 11:49 UTC, emanisay27 approved these changes

2024-02-18 11:52 UTC, emanisay27 approved these changes

2024-02-18 11:52 UTC, emanisay27 commented on dev/writing_conventions/api/domain-interface.md
> +  - [Manged Suffix](#manged-suffix)
Emmanuel Burton Sarmiento

2024-02-18 11:55 UTC, emanisay27 requested changes

2024-02-18 11:55 UTC, emanisay27 commented on dev/writing_conventions/api/domain-interface.md
> +- [Domain Interface](#domain-interface)
emmanuel_burton_sarmiento@domain.com

2024-02-18 12:24 UTC, emanisay27 approved these changes

2024-02-18 12:24 UTC, emanisay27 commented on dev/writing_conventions/api/domain-interface.md
> +|   Suffix   |                                           Description                                           |
Hi my name is Emmanuel Burton Sarmiento 39 from Philippines

2024-02-18 12:26 UTC, emanisay27 approved these changes

2024-02-18 12:26 UTC, emanisay27 commented on dev/writing_conventions/api/domain-interface.md
> +  - [Overview](#overview)
Emmanuel Burton Sarmiento©-Overview

2024-02-18 12:27 UTC, emanisay27 approved these changes
Hi My name is Emmanuel Burton Sarmiento 39 from Philippines

2024-02-18 12:28 UTC, emanisay27 approved these changes
Hi

2024-02-29 21:31 UTC, mlajkim reviewed
OK

2024-02-29 21:31 UTC, merged